Feature/product detail mobile
IsabelliBatista/Mentoria-Frontend pull request #2
Opened 2022-06-21 23:24 UTC by IsabelliBatista

### What kind of change does this PR introduce?
Feature

### What is this PR about and why are you making these changes?
This pr is about creating mentoring product detail page, all done in html and css

### How does it work?
On the product detail page, when opening the index we can see the responsive page and with all the elements made according to figma

--

2022-07-04 19:22 UTC, mxczpiscioneri requested changes

2022-07-04 19:22 UTC, mxczpiscioneri commented on Html/Product_Detail/index.html
> +  <link rel="stylesheet" href="/Html/Home/reset.css">
Com esse caminho iniciando com `/`, da certo a publicação do site? 
https://isabellibatista.github.io/Mentoria-Frontend

2022-07-04 19:22 UTC, mxczpiscioneri commented on Html/Product_Detail/index.html
> +        <img src="/Html/Home/img/logo-lockup.svg" alt="logo spencer williams fashion" class="logo-spencer">
Com esse caminho iniciando com `/`, da certo a publicação do site? 
https://isabellibatista.github.io/Mentoria-Frontend

2022-07-12 13:28 UTC, mxczpiscioneri requested changes

2022-07-12 13:28 UTC, mxczpiscioneri commented on Html/Lojinha/Product_Detail/index.html
> +  <link rel="stylesheet" href="../style.css">
Precisa pegar o CSS da Home?

2022-07-12 13:28 UTC, mxczpiscioneri commented on Html/Lojinha/Product_Detail/index.html
> +        <img src="../img/Logo-lockup.svg" alt="logo spencer williams fashion" class="logo-spencer">
Essa imagem mudou de nome? Seria `logo-lockup.svg`?

2022-07-12 13:30 UTC, IsabelliBatista commented on Html/Lojinha/Product_Detail/index.html
> +  <link rel="stylesheet" href="../style.css">
sim, tem estilos lá que estou reutilizando na página de detalhe do produto

2022-07-12 13:58 UTC, mxczpiscioneri approved these changes

2022-07-12 13:58 UTC, mxczpiscioneri commented on Html/Lojinha/Product_Detail/index.html
> +  <link rel="stylesheet" href="../style.css">
Isso pode ser um problema para refatorações e atualizações futuras. O ideal seria que se você for reutilizar um CSS, fosse colocasse em um arquivo a parte para saber o contexto dele.
Ex: `header.css`, `footer.css` ou até um `common.css`.
Deixando tudo no mesmo arquivo de css da home pode começar a misturar as classes, ter sobrescrita, carregar classes desnecessárias.

2022-07-12 15:19 UTC, merged